# -*- coding: utf-8 -*-
# Frozen five-state manual review artifact; not a new experiment driver.
import json,pathlib,statistics,subprocess
r=pathlib.Path.cwd();o=r/'results/a21';rows=[json.loads(s) for s in (o/'anatomy/rows.jsonl').read_text().splitlines() if s];parents=[2001,2005,2003,2007,2013];arms=['BASE_G','PRIMAL_G','DUAL_G','BOTH_G','RANDOM_G','BOTH_PG','RANDOM_PG'];by={(v['parent_id'],v['arm']):v for v in rows};cfg=json.loads((r/'configs/a21.json').read_text());summary=json.loads((o/'anatomy/summary.json').read_text());cost=json.loads((r/'results/jobs/a21-anatomy-01/job_receipt.json').read_text());reviews=json.loads((o/'INDEPENDENT_ARRAY_REVIEW.json').read_text());metas=[json.loads((o/'anatomy/caches'/f'{p}_17.json').read_text()) for p in parents]
assert len(rows)==35 and len(by)==35 and all(v['status']=='OK' for v in rows)
assert cost['source_commit']=='5c6bcb02bb4ab88f7b46f07bca4ca3f4e38a067c'
assert reviews['status']=='PASS' and summary['T0']['status']=='PASS'
assert all(by[p,'BOTH_G']['well_scaled_reference'] and by[p,'BOTH_G']['relative_H_step_error']<=.05 for p in parents)
assert all(by[p,'PRIMAL_G']['relative_H_step_error']>.05 and by[p,'RANDOM_G']['relative_H_step_error']>.05 for p in parents)
manifest={'schema':'a21.final_frozen_manifest.v1','source_freeze':cfg['source_freeze'],'physics_source_commit':cost['source_commit'],'report_source_commit':json.loads((r/'results/jobs/a21-local-report-final-02/job_receipt.json').read_text())['source_commit'],'independent_array_review_source_commit':json.loads((r/'results/jobs/a21-local-array-review-01/job_receipt.json').read_text())['source_commit'],'branch':'a21-two-sided-anatomy','parents':parents,'iterations':[17],'historically_exposed':True,'canonical_reference':'raw constrained full_GN_reference_None; no line-search scaling','reference_repair_count':0,'layout':{'real_material':54,'chart':'Re27 then Im27','cells':1728,'current_dimension':5184,'sources':6,'complex_channels_per_source':128,'real_measurements':1536,'real_packing':'source-major [Re128,Im128]','whitening':'original scalar 1/problem.scale, after real packing','B_state':'same full frozen state for all arms'},'arms':arms,'actual_rank':{'Galerkin':[56,56,56],'Petrov':[56,56,62]},'protected_new_rank':{'X':6,'Y':6,'XY':12,'random_G':12,'random_PG_trial':6,'random_PG_test':6},'full_workspace_count':5,'full_LU_count':5,'main_reduced_QPs':35,'QP_KKT_rtol':cfg['qp_kkt_rtol'],'backend_rtol':cfg['backend_consistency_rtol'],'identity_rtol':cfg['identity_rtol'],'normal_allowance_formula':cfg['normal_allowance_formula'],'physical_no_fallback':True,'no_jitter_or_pseudoinverse':True,'old_early_state_conflict':'PRESERVED; not re-run and not used as a late-state reference','source_config':cfg,'states':metas,'new_SHA256_checks':0,'cache_L_identity':'frozen runtime/state + source commit + paid LD images; full dense L and LU were not persisted','trial_test_coordinate_transforms_saved':True,'T0':summary['T0'],'no_truth_or_offline_labels_read':True,'T2_NN_nonlinear_solver_acceleration':'NOT_RUN_NOT_AUTHORIZED'}
(o/'A21_FROZEN_MANIFEST.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n')
gate=json.loads((o/'GATE_DECISION.json').read_text()); gate['automatic_status_preserved']=gate['status'];gate['status']='LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED';gate['final_scientific_status']=gate['status'];gate['final_scientific_review']='COMPLETED_BY_CODEX';gate['T0']['final_status']='PASS';gate['T1']['final_status']='PASS_FIVE_FROZEN_STATES';gate['scientific_review']={'scope':'OFFLINE ORACLE, five exposed Gaussian late frozen quadratics; no deployment or nonlinear claim','source':'A21_ORACLE_REPORT_ZH.md','independent_vector_review':'INDEPENDENT_ARRAY_REVIEW.json','complete_rows':35,'references_repaired':0,'all_raw_solver_bound_ratios_below_one':True,'max_raw_bound_ratio':max(v['bound_ratio'] for v in rows),'max_BOTH_G_relative_H_error':max(by[p,'BOTH_G']['relative_H_step_error'] for p in parents),'max_PRIMAL_weighted_solver_to_dual_ratio':max(v['weighted_solver_to_dual_ratio'] for v in reviews['reports'] if v['arm']=='PRIMAL_G'),'interpretation':'Exact primal response alone leaves a material-vector post-step dual defect; exact dual alone leaves amplified primal error. Both protected task banks restore the same frozen constrained optimum. Baseline errors involve both terms, not exclusively the dual.','petrov':'five-state fidelity passes; runtime/quality advantage over Galerkin not established; double basis memory and union rank62 disclosed','original_KKT_and_constraints_unchanged':True,'information_boundaries':'all teacher diagnostics paid offline; no runtime or training reuse','stop_after_five_states':True}
for s in gate['T1']['states']:s['final_scientific_review']='COMPLETED_BY_CODEX';s['final_status']='CONFIRMED_FROZEN_TWO_SIDED_FIDELITY'
(o/'GATE_DECISION.json').write_text(json.dumps(gate,indent=2,ensure_ascii=False)+'\n')
report=o/'A21_ORACLE_REPORT.md';text=report.read_text();text=text.replace('Final scientific interpretation: `CODEX_REVIEW_REQUIRED`.','Final scientific interpretation: `LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED`; see the signed-off Chinese report and GATE_DECISION.json.');text=text.replace('T2: `NOT_RUN_NOT_AUTHORIZED`. Codex final scientific assessment remains authoritative.','T2: `NOT_RUN_NOT_AUTHORIZED`. Codex final review is saved in `A21_ORACLE_REPORT_ZH.md` and `GATE_DECISION.json`.');text='> Final review: T0 PASS; T1 LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED for the five frozen exposed states. The automatic classifications below are preserved as pre-review evidence.\n\n'+text;report.write_text(text)
lines=['# A21 固定 rank 双侧 GN anatomy：科学报告','','**T0：PASS。T1：LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED。** 五个 iteration17 状态的35个主实验均有效；五态 BOTH_G 均通过有效尺度上的5% H-step目标，primal和匹配随机对照支持双侧任务信息的归因。该结论严格限定于五个历史暴露 Gaussian 对象的冻结受约束二次问题。成像质量、在线获取方法、部署收益和NN均未验证，实验已停止。','','## 冻结问题和检查','','冻结来源为 A20-R1 `'+cfg['source_freeze']+'`，物理执行源码为 `'+cost['source_commit']+'`。Maxwell、极化率、材料chart、白化、prior/LM、可行集、优化器和KKT门槛均复用原实现。每源64 receivers×2极化，共128个complex测量；packing为逐源 `[Re128,Im128]`，六源得到1536维实测量。材料为 `[Re27,Im27]` 共54维。','','每态只付费生成一次full state/LU和full J；canonical原始 constrained `full_GN_reference_None` 步未被alpha缩放，五个保存参考均重新通过原KKT审核，**没有重解或覆盖参考**。first/middle/last（2001、2003、2013）真实pack/白化/材料metric/B/B*/L/L*/F/F*/receiver/Schur及tied-adjoint测试通过。完整137项本地测试及随包tiny validation通过，最终56项A21回归与3项报告allowance回归也通过。','','[独立数组复核](INDEPENDENT_ARRAY_REVIEW.json)重新核对全部35套J/H/原始步/约束normal/乘子/缺陷向量、由已付费images重建JR、完整gap和solver-aware界；没有再跑Maxwell、QP或truth。所有参考H尺度为5.7973e-4–3.6324e-3，solver能量残差远低于它们；无参考分母需要用floor替代。','','## 全部五态主结果','','下表均为相对H_F-step误差 **百分比**；未使用floor改变分母。','','| Parent/17 | BASE_G | PRIMAL_G | DUAL_G | BOTH_G | RANDOM_G | BOTH_PG | RANDOM_PG |','|---|---:|---:|---:|---:|---:|---:|---:|']
for p in parents:
 values=[by[p,a]['relative_H_step_error']*100 for a in arms]
 lines.append('| '+str(p)+' | '+' | '.join(f'{x:.6g}%' for x in values)+' |')
lines+=['| Median | '+' | '.join(f"{statistics.median(by[p,a]['relative_H_step_error']*100 for p in parents):.6g}%" for a in arms)+' |','','BOTH_G最大相对误差为4.3956e-11（即4.3956e-9%），BOTH_PG为2.3345e-11。全部G实际trial/test/union rank=56/56/56，全部PG为56/56/62；G单基4.429688MiB，PG双基8.859375MiB。保护X/Y的真实独立新增rank各6、joint12，随机G12、随机PG两侧6/6完全匹配。未增加degree、补列或按结果选择删除方向。BASE_G重现原保存步的最坏相对差4.0584e-10，低于冻结1e-9门槛。','','## 为什么primal capture不是GN-step fidelity','','X_F描述沿正确材料步产生的六源完整Maxwell current响应；Y_F描述 **post-step residual** 被真实伴随传播回current空间的任务信息。这里保护的是L^{-1}B s_F和L^{-*}S* lift(Dᵀe_F)，而非旧KB材料注入。PRIMAL_G只知道正确响应，仍可能把post-step residual对其他材料方向的拉回算错；DUAL_G则反过来。','','完整材料向量分解为 `eta_direct = rho_F + delta_d + JRᵀ delta_p`。delta_d是54维材料向量，不是一个标量配对；报告和NPZ保存全部分量及 `eta_pair=rho_F+delta_d+JRᵀdelta_p-rho_R`。PRIMAL_G的epsilon_P为1.25e-14–5.25e-14，却保留显著的dual defect；DUAL_G的epsilon_D为2.13e-14–1.96e-12，却保留放大的primal项。两种单侧方法五态都未达5%。','','| Parent/17 | PRIMAL b_dual | PRIMAL b_primal | weighted solver/dual | BOTH_G HF abs error | raw HF bound | HF error/raw bound |','|---|---:|---:|---:|---:|---:|---:|']
for p in parents:
 pr=by[p,'PRIMAL_G'];bo=by[p,'BOTH_G'];rv=next(v for v in reviews['reports'] if v['parent_id']==p and v['arm']=='PRIMAL_G')
 values=[pr['b_dual'],pr['b_primal'],rv['weighted_solver_to_dual_ratio'],bo['absolute_H_step_error'],bo['bound_HF'],bo['bound_ratio']]
 lines.append('| '+str(p)+' | '+' | '.join(f'{x:.6g}' for x in values)+' |')
lines+=['','PRIMAL的加权solver项最多只是dual项的3.05e-11；其法锥allowance对毫米量级H-error亦可忽略。因此该反例不能用优化器误差或数值normal救场来解释。BOTH_G同时消除两项，匹配随机替换没有恢复步。','','**基线失败并非只有dual问题。** 基线的放大primal项在2001、2005、2007、2013的HR逆范数中更大；2003则dual更大。双侧保护支持“响应和残差拉回都必须保真”，不能把全部基线误差改写成单一dual原因。','','## 曲率、normal与solver-aware界','','所有H_F/H_R对称且SPD；各态固定Lambda最小特征值为3.43e-5。使用对称广义特征值beta，而非当前core条件数替代材料曲率；所有35臂的实测绝对H-error甚至都低于原始solver-aware界，最大error/bound=0.740595。数值normal allowance和floating allowance仍独立保存，不参与降低误差或改变5%目标。','','| Parent/17 | HF min | HF max | cond HF | BOTH_G mu | BOTH_G beta | sF H norm | full/reduced active |','|---|---:|---:|---:|---:|---:|---:|---|']
for p in parents:
 v=by[p,'BOTH_G'];values=[v['lambda_min_HF'],v['lambda_max_HF'],v['condition_HF'],v['mu'],v['beta'],v['reference_H_norm']]
 lines.append('| '+str(p)+' | '+' | '.join(f'{x:.6g}' for x in values)+f" | {v['active_constraints_F']}/{v['active_constraints_R']} |")
lines+=['','按冻结约定计算 `b_R=sqrt(eta_pairᵀ HR^{-1} eta_pair)`、`B_F=sqrt(beta)b_R`；normal来自独立活跃约束NNLS，n=-Aᵀmu，未用n=-gradient抹去缺陷。可行性、互补性、乘子符号和正定性逐套核对。完整gap直接计算并核验 `qF(sR)-qF(sF)=0.5||sR-sF||HF²-nFᵀ(sR-sF)+rhoFᵀ(sR-sF)`。BOTH臂直接gap约1e-20，包含微小负数，这是减去近等二次目标的舍入尺度，已原样保留；不能解释为超过full optimum。','','### 逐态解释','','- **2001**：PRIMAL的dual仍大；DUAL去掉dual后仍有80.65%误差。BASE有两项部分抵消（Euclidean cancellation≈0.714），仍未保真；BOTH保留2个full活跃约束，恢复原步。','- **2005**：BASE放大primal在HR逆范数中约为dual的3.3倍；PRIMAL改正响应却仍有420.88%误差，DUAL仍98.63%。BOTH恢复2个活跃约束；约6.8e4的HF条件数需显式报告，却没有违反bound。','- **2003**：BASE的加权dual大于加权primal。原参考含10个活跃约束，PRIMAL/DUAL各12；BOTH恢复10。原参考rho_F≈2.409e-14导致BOTH最明显的数值误差，但仅1.597e-13绝对H-error，受原始2.551e-13界覆盖，仍远低于5%。','- **2007**：BASE/DUAL没有活跃约束，full参考为1；PRIMAL变为2，BOTH恢复1。DUAL消除pullback defect后仍100.78%，显示放大primal不能忽略；不存在core、KKT或分母失效。','- **2013**：BASE放大primal远大于dual，DUAL仍98.73%；PRIMAL保留dual则111.38%。BOTH恢复full的3个活跃约束，误差回到数值尺度。','','所有状态均可判，缺失/invalid/reference repair均为0。current core最坏条件数890.664仍通过原安全门；没有Petrov自动切换、full fallback、jitter或伪逆。Petrov两个oracle臂同样通过，但union rank62及双倍基内存必须和G分开；其优势尚未建立。','','## 费用、失败与交付','','[COST_LEDGER](COST_LEDGER.jsonl)、[JOB_LEDGER](JOB_LEDGER.jsonl)、[失败](FAILURE_LEDGER.jsonl)和[最终预算](BUDGET_FINAL.json)记录所有验证、错误、传输和报告。物理job CPU267.359375秒、GPU占用281.661815秒；共享full-J1620 RHS、验证JVP36/VJP36、oracle primal30/adjoint30、full state30 RHS，共1782 full solve RHS；F/F*/L/L*各163/103/631/171，aggregate1068不能再叠加。这些是offline机制实验成本，不是部署速度测试。原full-state L/Goff各30 RHS、receiver、LU、QR和QP分账见[动作解释](ACTION_ACCOUNTING.md)。','','五份共享缓存和35套诊断向量均已保存，物理job只有35个主QP；没有full-reference repair或物理重跑。压缩archive首次超过25秒CPU上限，失败及25.953125秒CPU保留；重新用唯一命名STORED archive转移已存在结果，没有重跑实验。报告层absolute allowance接线冲突和只读账本核对脚本的一次失败也单列。原A20/R1账本与源码未改动；旧early复现冲突及voxel reference失败保留。','','[图表](figures/)及[rawdata](rawdata/)包括全部五态误差/界、加权stationarity、曲率、normal work和双基内存。各项指标、余下完整向量及六源capture在[A21_METRICS.csv](A21_METRICS.csv)、[per_state](per_state/)和缓存中。','','结论是冻结受约束GN任务的**双侧保真机制得到验证**，并非在线算法或非线性成像已完成。T2、degree扩展、NN、nonlinear reconstruction、solver acceleration和发布均NOT_RUN；完成五-state anatomy后停止。','']
(o/'A21_ORACLE_REPORT_ZH.md').write_text('\n'.join(lines))
start=['# A21：五态双侧 GN anatomy 已完成','','**T0 PASS；T1 LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED。** 五个历史暴露 late states、35个固定rank主实验完整有效。BOTH_G最大相对H-error 4.40e-11，PRIMAL_G中位262.00%，匹配RANDOM_G中位280.15%。双侧oracle恢复原冻结受约束full-GN步；在线/成像/部署收益尚未验证。','','先读[中文科学报告](A21_ORACLE_REPORT_ZH.md)，再查[Gate](GATE_DECISION.json)、[全部指标](A21_METRICS.csv)。','','- [Backend接线](A21_BACKEND_MAPPING.md)、[冻结manifest](A21_FROZEN_MANIFEST.json)、[数值约定](A21_NUMERICAL_CONVENTIONS.md)。','- [逐态记录](per_state/)、[原始cache](anatomy/caches/)、[诊断向量](anatomy/diagnostics/)、[独立数组复核](INDEPENDENT_ARRAY_REVIEW.json)。','- [图表](figures/)、[图表原始数据](rawdata/)、[自动初审报告](A21_ORACLE_REPORT.md)。','- [完整T0](validation/T0.json)、[真实T0与summary](anatomy/summary.json)、[复现命令](REPRODUCE.md)。','- [成本](COST_LEDGER.jsonl)、[失败](FAILURE_LEDGER.jsonl)、[动作口径](ACTION_ACCOUNTING.md)、[最终预算](BUDGET_FINAL.json)。','','物理冻结源码 `'+cost['source_commit']+'`；报告源码见冻结manifest和独立job receipts。参考未缩放、未修复；原A20/R1源码、账本、结果、release保持原样，未重新计算SHA256。','','实验已经停止。NN、nonlinear reconstruction、degree增加、solver acceleration、T2和A21发布均NOT_RUN。']
(o/'START_HERE.md').write_text('\n'.join(start)+'\n')
back=o/'A21_BACKEND_MAPPING.md';back.write_text(back.read_text()+"\n## Executed A21 verification\n\nFive late references passed without repair; real T0 (2001/2003/2013) passed. All35 arms and independent saved-array review passed. Physical source `"+cost['source_commit']+"`; final review and exact numerical evidence: `A21_ORACLE_REPORT_ZH.md`, `A21_FROZEN_MANIFEST.json`, `INDEPENDENT_ARRAY_REVIEW.json`. No new SHA256 checks.\n")
rep=json.loads((o/'REPORT_MANIFEST.json').read_text());rep['scientific_judgment']='LATE_GN_TWO_SIDED_FIDELITY_CONFIRMED';rep['final_review_source']='A21_ORACLE_REPORT_ZH.md';rep['paths']+=['results/a21/START_HERE.md','results/a21/A21_ORACLE_REPORT_ZH.md','results/a21/A21_FROZEN_MANIFEST.json','results/a21/INDEPENDENT_ARRAY_REVIEW.json'];(o/'REPORT_MANIFEST.json').write_text(json.dumps(rep,indent=2)+'\n')
print('Frozen manifest, final reviewed gate and Chinese scientific report written')
